[project]
dynamic = ["dependencies", "optional-dependencies"]
[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
optional-dependencies = { dev = { file = ["requirements-dev.txt"] } }


[tool.ruff]
indent-width = 2

[tool.ruff.lint]
exclude = ["./*"]
